### ISSUE TITLE
Setting config doesn't work?

### ISSUE THREAD

**Issue by esjewett** [gajus/gitdown#25]
```
var gitdown = require('gitdown');
var config = gitdown.config;
config.gitinfo.gitPath = './docs';
gitdown.config = config;
```

results in error:

```
config.gitinfo.gitPath = './docs';
      ^
TypeError: Cannot read property 'gitinfo' of undefined
```

This seems to be what is documented in the README for gitdown, but doesn't seem to be working. Am I doing something wrong? This is in gulp.

**Comment by gajus** [comment]
What is the output of `console.log(gitdown.config)`?

**Comment by esjewett** [comment]
undefined, it seems

**Comment by gajus** [comment]
You have not initialised `Gitdown`:

```js
var gitdown,
    config;

gitdown = Gitdown('Direct Markdown');
// or...
// gitdown = Gitdown.read('markdown.md');

config = gitdown.config;
```

**Comment by esjewett** [comment]
So would the gulp example then need to be the following?

```
var gulp = require('gulp'),
    Gitdown = require('gitdown');

gulp.task('gitdown', function () {
    var gitdown = Gitdown.read('.gitdown/README.md');
    var config = gitdown.config;
    config.gitinfo.gitPath = './docs';
    gitdown.config = config;

    return gitdown
        .write('README.md');
});

gulp.task('watch', function () {
    gulp.watch(['./.gitdown/*'], ['gitdown']);
});
```

I'll give that a try. Thanks.

**Comment by esjewett** [comment]
Ok, this (or rather a variation on it) seems to work. But maybe I'm missing the point of this config settings. I assumed that it would change the comment at the top of the generated file to point to the right path (though I'd actually prefer to get rid of the comment entirely). I'll just have a look at the source and see what the situation is. Thanks!

**Comment by gajus** [comment]
Which part of the docs made you thin that way? I will improve it.

**Comment by esjewett** [comment]
I don't think anything did, I just assumed incorrectly :) What I ended up doing was just saying

```
var Gitdown = require('gitdown');
Gitdown.notice = function () { return ''; };
```

Maybe add that to the doc for those wishing to control the notice?

Also, just FYI, the whole thing is working great now. Thanks for making this tool and alerting me to the fact that it exists!
