### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by mdreizin** [gajus/gitdown#28]
`Gitdown.read('.gitdown/README.md').write('README.md')`

Gitdown uses invalid encoding and as result [npm](https://www.npmjs.com) displays it incorrectly.

https://www.npmjs.com/package/gitdown
https://www.npmjs.com/package/gulp-webpack-build
etc.

**Comment by gajus** [comment]
Please provide more debug information. If it is an easy fix, I will sort it out ASAP.

**Comment by mdreizin** [comment]
@gajus what kind of debug information I should provide?

github parses `README.md` correctly, but npm can't parse it and escapes `"` with `&apos;`. 

Unfortunately, it appears after `gitdown` processing.

`md`-file will display correctly on `npm` if you use `md`-file without any `gitdown` processing.

**Comment by mdreizin** [comment]
@gajus Have you got any idea why npm displays `gitdown`-files incorrectly?

**Comment by gajus** [comment]
This is not encoding issue with gitdown. It is the markdown processor that npmjs.com is using, https://github.com/npm/newww/issues/622. I have raised an issue.

**Comment by gajus** [comment]
Fixed by removing HTML comments from the output.

**Comment by mdreizin** [comment]
@gajus Thanks!
