### ISSUE TITLE
AppVeyor badge

### ISSUE THREAD

**Issue by mdreizin** [gajus/gitdown#35]
As developer I would like to have AppVeyor [badge](http://www.appveyor.com/docs/status-badges) with retina support.

**Comment by gajus** [comment]
Which badge, though?

**Comment by mdreizin** [comment]
@gajus build status

[![AppVeyor build status](https://ci.appveyor.com/api/projects/status/github/mdreizin/webpack-config?svg=true&branch=master)](https://ci.appveyor.com/project/mdreizin/webpack-config)
