### ISSUE TITLE
codeclimate

### ISSUE THREAD

**Issue by mdreizin** [gajus/gitdown#44]
codeclimate badges generate invalid markdown:

https://github.com/gajus/gitdown/blob/master/src/helpers/badge.js#L131
https://github.com/gajus/gitdown/blob/master/src/helpers/badge.js#L141
https://github.com/gajus/gitdown/blob/master/tests/helpers/badge.js#L145

Now it adds double `github` to url:

https://img.shields.io/codeclimate/coverage/github/github/mdreizin/webpack-config.svg?style=flat-square
https://img.shields.io/codeclimate/github/github/mdreizin/webpack-config.svg?style=flat-square

but it should be:

https://img.shields.io/codeclimate/coverage/github/mdreizin/webpack-config.svg?style=flat-square
https://img.shields.io/codeclimate/github/mdreizin/webpack-config.svg?style=flat-square

**Comment by gajus** [comment]
Please submit a PR.
