### ISSUE TITLE
security vulnerability, gitdown takes dependency on vulnerable version of url-extractor

### ISSUE THREAD

**Issue by nickharris** [gajus/gitdown#52]
`npm audit` details as follows
  Package         marked
  Patched in      >=0.6.2
  Dependency of   gitdown [dev]
  Path            gitdown > url-extractor > marked
  More info       https://npmjs.com/advisories/812

linked issue to url-extractor https://github.com/gajus/url-extractor/issues/4

**Comment by nickharris** [comment]
thanks for the quick turnaround @gajus, any chance you can push the updated version to npmjs?

**Comment by brettz9** [comment]
This doesn't seem to have gotten published despite the semantic versioning in the commit. I noticed that the `package.json` version is several patch versions behind as well.
