### ISSUE TITLE
`get-urls` use of `re2` and compilation

### ISSUE THREAD

**Issue by brettz9** [gajus/gitdown#60]
This is an FYI (and to the limited extent I understand it), that after an update on `eslint-plugin-jsdoc`, apparently due to an issue similar to https://github.com/uhop/node-re2/issues/79 , i.e., the error that re2 "was compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 83", but starting over with `node_modules` and `package-lock.json` or adding the solution it references at https://github.com/uhop/node-re2/wiki/Problem:-ABI-mismatch-in-Electron , and https://github.com/uhop/install-artifact-from-github/wiki/Installing to add `DEVELOPMENT_SKIP_GETTING_ASSET=1` before the `babel-node` calls in the `check-readme` script did not help. I'm using nvm and when I switched back from Node 12 as I was using to Node 14, I was able to get through our husky hook (which uses gitdown) without complaint.

Just a heads up since the dependency chain of gitdown, `get-urls` -> `url-regex-safe` -> `re2` leads to re2 and others may run into this issue. I'm not sure any other action is called for.

**Comment by gajus** [comment]
Thank you for the heads up. :-)
