### ISSUE TITLE
Support for links on npm

### ISSUE THREAD

**Issue by brettz9** [gajus/gitdown#63]
In making a document which also works on npmjs.com, we need support for links which are prefixed with `user-content-`. GitHub supports this prefix in addition to unprefixed ones, while npmjs.com requires it.

For example with `eslint-plugin-jsdoc`, the Markdown `Settings` heading gets turned into the anchor `user-content-settings`, and the HTML anchor `eslint-plugin-jsdoc-settings` becomes `user-content-eslint-plugin-jsdoc-settings` with no other anchors available.

I'm guessing the article ID passed on to your contents generators may need to be prefixed with `user-content-`.

This would fix our https://github.com/gajus/eslint-plugin-jsdoc/issues/707

**Comment by gajus** [comment]
Seems like a reasonable fix. If you are available to contribute, would quickly release it.
